- hosts: tomcat
  become: true
  vars:
    filepath: /opt/tomcat9/conf/
  tasks:
    - name: Ansible Template Example
      template:
        src: server.xml.j2
        dest: "{{ filepath }}/server.xml"
      tags: updatefile
